import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Boys Gym - Open 24/7",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className="text-white" 
      style={{ 
        background: 'url(background.jpg)', 
        backgroundSize: '100% 100%', 
        backgroundRepeat: 'no-repeat', 
        objectFit: 'cover'
      }}
      >
        {children}
      </body>
    </html>
  );
}
